### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by dgiagio** [lucaslorentz/durabletask-extensions#33]
Hi Lucas,

Our company uses Durable Task in Production with SQL Server, but we're interested in migrating to PostgreSQL since that database it's used by most of our systems already.

Would you say your EF Core PostgreSQL extension for Durable Task is ready to be used in Production? Do you have any knowledge of it being used that way currently?

I tried to reach out to you directly to ask about this, but since I couldn't find an email address anywhere, I'm opening this issue instead.

Thanks.

**Comment by lucaslorentz** [comment]
Hey, Diego,

As far as I know, I'm the only one using this project in production, but I use MySql instead of Postgres. MySql and Postgres storage implementations share a lot of code, but locking queries, in particular, are different.

I use it in a low-traffic system, and it's working flawlessly. Numbers from the last 14 days:
~ 3.874.124 orchestration events
~ 179.963 orchestrations executions

What I use:
- LLL.DurableTask.Client
- LLL.DurableTask.Worker
- LLL.DurableTask.Api
- LLL.DurableTask.Ui
- LLL.DurableTask.EFCore
- LLL.DurableTask.EFCore.MySql

I don't use the other packages at the moment.
I personally think the UI I implemented is a great experience to monitor orchestrations.

It would be nice for this project to mature a bit more, but for that we need it to be more battle-tested and more contributors. If you have some time, give it a try and do a proof of concept.

Worth mentioning as well that it is a bit slower than SQL Server official storage. I think it's due to the fact we use EFCore and they have fewer abstractions on top of the database. The good thing is that as EF Core becomes more performant, our performance will improve as well.

**Comment by lucaslorentz** [comment]
Another interesting thing is that I do use 2 "maintenance" orchestrations implemented outside this repo:

- One to clean up old orchestrations. Cleaning up old orchestrations is a heavy operation because I didn't setup any table partitioning because EF Core doesn't support it. In order to keep it lightweight, I run cleanup every 10 min, and it deletes everything older than 14 days in batches of 50.

- Another one to easily rewind all failed orchestrations, the UI doesn't support bulk rewinding yet. If some third-party system is down for example and I end up with too many failed orchestrations, I just kick off this one and it rewinds all failed orchestrations to retry the last failed action.

I can share code of both orchestrations in case you're interested. They're pretty straight-forward.
