### ISSUE TITLE
How to pass variables in the BPMN worker

### ISSUE THREAD

**Issue by chandusekhar** [lucaslorentz/durabletask-extensions#36]
Great project to start with the Durable Tasks. Can you please help on how to pass variables in the BPMN worker

**Comment by lucaslorentz** [comment]
I followed the convention/definitions from Camunda in the BPMN worker, because BPMN by itself doesn't have scripting languages, variables, and definitions of input/outputs.
 
Download Camunda Modeler and have a look at the examples at https://github.com/lucaslorentz/durabletask-extensions/tree/main/samples/BpmnWorker/Workflows 

Capturing the output of an activity into a variable:
<img width="885" alt="Screenshot 2024-07-27 at 20 33 53" src="https://github.com/user-attachments/assets/272a38b8-ee23-438c-a393-a5f97fb05f30">

Passing the saved variable to next activity:
<img width="885" alt="Screenshot 2024-07-27 at 20 34 22" src="https://github.com/user-attachments/assets/9303bd1e-824c-420a-9184-a60172b5b3f0">

Bear in mind that the BPMN runner I implemented was quite experimental, just to understand how much DurableTask concepts align with BPMN and the feasibility of running BPMN in durable task.
